# Assignment-1

### 5 interesting functions related to PyTorch tensors 

PyTorch along with Tensorflow are one of the biggest AI and machine learning library for Python,
A tensor is vector or a matrix, so a tensor can have 1 row or 1 column to be a vector or as many rows and columns you need to be a matrix. Tensors have indices, representing one value of the tensor.
Infact, in machine learning the so called tensors play a big role that's the  reason that Googles ML library is called Tensorflow.

An short introduction about PyTorch and about the chosen functions. 
1. mm_()
2. FloatTensor()
3. apply_()
4. cumsum()
5. mean_()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - mm()

Performs the matrix multiplication on tensors

In [2]:
# Example 1
tensor = torch.tensor([[7,8,9]])
tensor2 = torch.tensor([[3],[4],[3]])
tensor.mm(tensor2)

tensor([[80]])

Matrix multiplication of 1x3 and 3x1 tensores

In [3]:
# Example 2
tensor = torch.empty((5,4), dtype=int)
tensor.random_(0,20)

tensor([[16,  3, 15,  0],
        [ 4,  2, 16, 11],
        [ 4, 13, 13,  5],
        [13,  2,  4, 10],
        [ 2,  3,  5, 18]])

In [4]:
tensor2 = torch.empty((4,6), dtype=int)
tensor2.random_(0,20)

tensor([[10, 19, 18, 11,  7, 19],
        [18,  4, 14, 11, 13,  2],
        [13, 18,  8, 10, 17,  5],
        [14,  3, 11,  5, 16, 12]])

In [5]:
tensor.mm(tensor2)

tensor([[409, 586, 450, 359, 406, 385],
        [438, 405, 349, 281, 502, 292],
        [513, 377, 413, 342, 498, 227],
        [358, 357, 404, 255, 345, 391],
        [391, 194, 316, 195, 426, 285]])

Matrix multiplication of 3x2 and 2x3 tensors

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.empty((4,2), dtype=int)
tensor.random_(0,20)
tensor2 = torch.empty((4,2), dtype=int)
tensor2.random_(0, 20)
tensor.mm(tensor2)

RuntimeError: size mismatch, m1: [4 x 2], m2: [4 x 2] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41

We can see that, we can't multiply 3x2 with 3x2 because column count of the first tensor has to be equal to row count of the second.

Matrix multiplication if very importend for machine learning and will be used in various implementations

### Function 2 - FloatTensor()
Converts the input integers arrays to Float on Tensors

In [7]:
float_vector = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(float_vector)
print(float_vector.dtype)

tensor([1., 2., 3., 4., 5., 6.])
torch.float32


In [8]:
float_2 = torch.FloatTensor([-7, 8, 5, -9, 0, 3])
print(float_2)
print(float_2.dtype)

tensor([-7.,  8.,  5., -9.,  0.,  3.])
torch.float32


We can include negative integers too

In [9]:
float_3 = torch.FloatTensor([-7/2, 8+9, 5, -9, 0, 3])
print(float_2)
print(float_2.dtype)

tensor([-7.,  8.,  5., -9.,  0.,  3.])
torch.float32


In [10]:
float_2 = torch.FloatTensor([-5/0, 4*2, 5-3, -9+1, 0*6, 3])
print(float_2)
print(float_2.dtype)

ZeroDivisionError: division by zero

We can't use anything by 0

We can use this function to get the floating arrays

## Function 3 - apply()

Applies a function inplace to evry element of the Tensor

In [11]:
# Example 1 - 
tensor = torch.empty((3,2), dtype=torch.int8)
tensor.random_(-10,10)

tensor([[  8,   4],
        [ -8,   0],
        [  0, -10]], dtype=torch.int8)

In [12]:
def absolute(e):
    return abs(e)

tensor.apply_(absolute)

tensor([[ 8,  4],
        [ 8,  0],
        [ 0, 10]], dtype=torch.int8)

Create a function and apply it to a tensor to get absolute of all elements

In [13]:
# Example 2
def square(e):
    return e*e

tensor.apply_(square)

tensor([[ 64,  16],
        [ 64,   0],
        [  0, 100]], dtype=torch.int8)

Create a function and apply it to a tensor to get square of all elements

In [14]:
# Example 3 
def stringify(e):
    return str(e)

tensor.apply_(stringify)

TypeError: an integer is required (got type str)

You can not change the dype of a tensor's element

We can use this function when we want to make some operation on a tensor

## Function 4 - cumsum()

Returns the cumilative sum of all elements in a tensor

In [15]:
# Example 1
tensor = torch.randint(high=10, size=(1,6))
tensor

tensor([[7, 3, 3, 6, 1, 0]])

In [16]:
tensor.cumsum(dim=1)

tensor([[ 7, 10, 13, 19, 20, 20]])

Return the cumsum of a 1d tensor

In [17]:
# Example 2
tensor = torch.randint(high=10, size=(4,3))
tensor

tensor([[4, 7, 6],
        [5, 3, 6],
        [6, 8, 9],
        [8, 3, 3]])

In [18]:
tensor.cumsum(dim=0)

tensor([[ 4,  7,  6],
        [ 9, 10, 12],
        [15, 18, 21],
        [23, 21, 24]])

Add all elements from top the bottom

In [19]:
# Example 3
tensor.cumsum(dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

You can not use a dimension bigger than tensors

We can use this function to visualise for cumilative sum of a vector

## Function 5 - mean()

This returns the mean of all elements in the tensor

In [20]:
# Example 1 
tensor = torch.empty(10)
tensor.random_(0,50)

tensor([ 1., 28.,  4., 25.,  2.,  4., 31.,  6., 17., 40.])

In [21]:
tensor.mean()

tensor(15.8000)

This is for 1-D Tensor

In [22]:
# Example 2
tensor = torch.empty((4,3))
tensor.random_(0,50)

tensor([[12., 30., 39.],
        [34., 29., 12.],
        [ 7., 11.,  3.],
        [39., 23., 36.]])

In [23]:
tensor.mean()

tensor(22.9167)

This is for 2-D Tensor

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
tensor = torch.empty((3,3), dtype=int)
tensor.random_(0,50)

tensor([[ 5,  9, 20],
        [18,  3,  9],
        [38, 26, 18]])

In [25]:
tensor.mean()

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

We can not take mean of long values using this function
(Can only calculate the mean of floating types)

Mean can be used for various reasons. For example we can take the mean of error to evaluate our model

## Conclusion

This notebook covered some examples from various functions with example and  explaination

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://linuxhint.com/pytorch_linear_regression_tutorial/

In [26]:
!pip install jovian --upgrade --quiet

In [27]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
